create table doctor(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) not null,
    post varchar(30) not null,
    job_time_begin time,
    job_time_end time
);

create table patient(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) not null ,
    disease varchar(20) not null ,
    age int not null
);

create table doctor_patient(
    doctor_id int,
    patient_id int
);

insert into doctor(name, post, job_time_begin, job_time_end) values('Кондрушин Иля Евгеньевич', 'Травматолог', '8:00', '12:00');
insert into doctor(name, post, job_time_begin, job_time_end) values('Кулаков Виктор Андреевич', 'Психиатр', '12:30', '16:30');

insert into patient(name, disease, age) values('Скрипка Андрей Викторович', 'Шизофрения', 20);
insert into patient(name, disease, age) values('Кобзев Василий Васильевич', 'Дипрессия', 20);
insert into patient(name, disease, age) values('Ширяев Алексей Павлович', 'Разрыв миниска', 23);
insert into patient(name, disease, age) values('Титаренко Дмитрий Юрьевич', 'Перелом лучевой кости', 20);

insert into doctor_patient(doctor_id, patient_id) values(1, 3);
insert into doctor_patient(doctor_id, patient_id) values(1, 4);
insert into doctor_patient(doctor_id, patient_id) values(2, 1);
insert into doctor_patient(doctor_id, patient_id) values(2, 2);
