create table doctor(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(30) not null,
    last_name varchar(30) not null,
    patronymic varchar(30) not null,
    post varchar(30) not null,
    job_time_begin time,
    job_time_end time
);

create table patient(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(30) not null,
    last_name varchar(30) not null,
    patronymic varchar(30) not null,
    disease varchar(20) not null ,
    age int not null
);

create table doctor_patient(
    doctor_id int,
    patient_id int
);

insert into doctor(first_name, last_name, patronymic, post, job_time_begin, job_time_end) values('Илья', 'Кондрушин', 'Евгеньич', 'Травматолог', '8:00', '12:00');
insert into doctor(first_name, last_name, patronymic, post, job_time_begin, job_time_end) values('Виктор', 'Кулаков', 'Андреевич', 'Психиатр', '12:30', '16:30');

insert into patient(first_name, last_name, patronymic, disease, age) values('Андрей','Скрипка','Викторович', 'Шизофрения', 20);
insert into patient(first_name, last_name, patronymic, disease, age) values('Василий','Кобзев','Васильевич', 'Дипрессия', 20);
insert into patient(first_name, last_name, patronymic, disease, age) values('Алексей','Ширяев','Павлович', 'Разрыв миниска', 23);
insert into patient(first_name, last_name, patronymic, disease, age) values('Дмитрий','Титаренко','Юрьевич', 'Перелом лучевой кости', 20);

insert into doctor_patient(doctor_id, patient_id) values(1, 3);
insert into doctor_patient(doctor_id, patient_id) values(1, 4);
insert into doctor_patient(doctor_id, patient_id) values(2, 1);
insert into doctor_patient(doctor_id, patient_id) values(2, 2);
